
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLKS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class CHITIET_HDGU
{

    public int MA_CTHDGU { get; set; }

    public int MA_HD { get; set; }

    public int MA_LUOTGU { get; set; }

    public Nullable<decimal> TRIGIA_CTHDGU { get; set; }

    public Nullable<System.DateTime> THOIGIANLAP_CTHDGU { get; set; }



    public virtual LUOTGIATUI LUOTGIATUI { get; set; }

    public virtual HOADON HOADON { get; set; }

}

}
