
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLKS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LOAIPHONG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LOAIPHONG()
    {

        this.PHONG = new HashSet<PHONG>();

    }


    public int MA_LP { get; set; }

    public string TEN_LP { get; set; }

    public Nullable<decimal> DONGIA_LP { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHONG> PHONG { get; set; }

}

}
