
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLKS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LUOTGIATUI
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LUOTGIATUI()
    {

        this.CHITIET_HDGU = new HashSet<CHITIET_HDGU>();

    }


    public int MA_LUOTGU { get; set; }

    public int MA_LOAIGU { get; set; }

    public Nullable<int> SOKILOGRAM_LUOTGU { get; set; }

    public Nullable<System.DateTime> NGAYBATDAU_LUOTGU { get; set; }

    public Nullable<System.DateTime> NGAYKETTHUC_LUOTGU { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIET_HDGU> CHITIET_HDGU { get; set; }

    public virtual LOAIGIATUI LOAIGIATUI { get; set; }

}

}
