
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLKS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class MATHANG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MATHANG()
    {

        this.CHITIET_HDAU = new HashSet<CHITIET_HDAU>();

    }


    public int MA_MH { get; set; }

    public string TEN_MH { get; set; }

    public Nullable<decimal> DONGIA_MH { get; set; }

    public Nullable<System.DateTime> NGAYNHAP_MH { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIET_HDAU> CHITIET_HDAU { get; set; }

}

}
