
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLKS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class NHANVIEN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NHANVIEN()
    {

        this.HOADON = new HashSet<HOADON>();

    }


    public int MA_NV { get; set; }

    public int MA_TK { get; set; }

    public string HOTEN_NV { get; set; }

    public Nullable<bool> GIOITINH_NV { get; set; }

    public Nullable<System.DateTime> NGAYSINH_NV { get; set; }

    public string SODIENTHOAI_NV { get; set; }

    public string CHUCVU_NV { get; set; }

    public string DIACHI_NV { get; set; }

    public Nullable<System.DateTime> NGAYVAOLAM_NV { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HOADON> HOADON { get; set; }

    public virtual TAIKHOAN TAIKHOAN { get; set; }

}

}
