
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLKS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PHONG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PHONG()
    {

        this.CHITIET_HDLT = new HashSet<CHITIET_HDLT>();

    }


    public int MA_PHONG { get; set; }

    public int MA_LP { get; set; }

    public string TINHTRANG_PHONG { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIET_HDLT> CHITIET_HDLT { get; set; }

    public virtual LOAIPHONG LOAIPHONG { get; set; }

}

}
